object testArith extends App {
  println("gcd(15, 12) = " + arithmetic.gcd(15, 12))
  println("lcm(15, 12) = " + arithmetic.lcm(15, 12))
  println("gcd(13, 12) = " + arithmetic.gcd(13, 12))
  println("gcd(-13, 12) = " + arithmetic.gcd(-13, 12))
  println("phi(9)= " + arithmetic.phi(9))
  println("sqrt(49) = " + arithmetic.sqrt(49))
  println("sqrt(37) = " + arithmetic.sqrt(37))
  println("sqrt(35) = " + arithmetic.sqrt(35))
  println("log(64) = " + arithmetic.log(64))
  println("log(130) = " + arithmetic.log(130))
  println("log(9) = " + arithmetic.log(9))
  println("log(0) = " + arithmetic.log(0))
  println("isPrime(23) = " + arithmetic.isPrime(23))
  println("isPrime(59) = " + arithmetic.isPrime(59))
  println("isPrime(75) = " + arithmetic.isPrime(75))
}